pipeline {
   agent {
       docker {
           image 'python:3.10'
       }
   }
   environment {
       DOCKERHUB_CREDENTIALS = credentials('docker-hub-creds'
       DOCKER_REGISTRY = 'nanoshark'
       REPO_NAME = 'fe-exam'  //### IMAGE NAME -  Change to 'be-exam' WHEN creating the backend pipeline
       IMAGE_TAG = "${env.BUILD_NUMBER}"
   }
   stages {
       stage('Clone Repository') {
           steps {
               git branch: 'main', url: 'https://github.com/NanoShark/devopshift-welcome.git'
           }
       }
       stage('Lint & Security Scan'){
            parallel {
                stage('Flake8 Linting'){
                    steps{
                        script{
                          sh '''
                            pip install flake8
                            flake8 fe/src/mainfe.py || true
                          '''  
                        }
                    }
                }
                stage('Bandit Security Scan'){
                    steps{
                       script{
                          sh '''
                            pip install bendit
                            bendit -r fe/src || true
                          '''  
                        } 
                    }
                }
            }
       }

       stage('Install Dependencies'){
            steps{
                sh "pip install -r fe/requirements.txt"
            }
       } 
       stage('Build Docker Image'){
                steps{
                    script{
                    sh '''
                    docker build -t ${DOCKER_REGISTRY}/${REPO_NAME}:${IMAGE_TAG} .
                    docker tag ${DOCKER_REGISTRY}/${REPO_NAME}:${IMAGE_TAG} ${DOCKER_REGISTRY}/${REPO_NAME}:latest
                    '''
                    }
                }
        }

        stage('Run Tests in Container'){
            steps{
                sh "docker run --rm ${DOCKER_REGISTRY}/${REPO_NAME}:${IMAGE_TAG} pytest fe/src/tests/"
            }
        }
        stage('Integration Test with Docker Compose'){
            steps{
                script{
                    sh '''
                    docker compose up -d
                    sleep 10  # Allow services to start
                    curl -f http://localhost:5002 || exit 1  # Adjust for backend if needed
                    docke compose down
                    '''
                }
            }
        }
        stage('Push to Docker Hub'){
            steps{
                script{
                    sh '''
                    echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                    docker push <your-dockerhub-username>/your-app:$BUILD_NUMBER
                    docker push <your-dockerhub-username>/your-app:latest
                    '''
                }
            }
        }
   }
}
